### PR TITLE
Correctly exposing floats from icsnVC40.h

### PR DESCRIPTION
**Pull request by pierreluctg**
Before this fix the floats from icsnVC40.h like the timestamp scaling
values where converted to integers.

### CODE REVIEW

**Comment by pierreluctg** [comment]
Hi @drebbe-intrepid can you please let me know if this is the correct process to get a fix in this repo?

Thank you

**Comment by drebbe-intrepid** [comment]
Give me a few days and I'll look at it and test it then merge it.

**Comment by drebbe-intrepid** [comment]
Thank you for catching this, initial testing looks good. Once I do complete testing I'll release a new version.

**Comment by drebbe-intrepid** [comment]
This change is live in version 2.5.

**Pull request merged**
