### PR TITLE
Allocating memory for the spyMessages 

### PR DESCRIPTION
**Pull request by pierreluctg**
Under some condition there was not enough heap space for the received messages buffer.

### CODE REVIEW

**Comment by pierreluctg** [comment]
Hi @drebbe-intrepid please have a look.

Thank you

**Comment by drebbe-intrepid** [comment]
Thanks for the commit, I'll look at it soon. Can you provide details on the condition where this happens? I'm assuming its on some type of embedded/ARM system.

**Comment by pierreluctg** [comment]
This issue was actually discovered on Windows. I was not able to reproduce when using `python.exe` but the issue is showing up when executing the python script via another executable.

**Comment by pierreluctg** [comment]
@drebbe-intrepid the issue can also be replicated on Linux.

```python
import resource
import ics

# Limit the stack size to demonstrate the issue
# The default limit will be different for various environment
# so this is only to be able to cause the failure for demonstration purpose.
print "Default limit:", resource.getrlimit(resource.RLIMIT_STACK)
resource.setrlimit(resource.RLIMIT_STACK, (2**2, -1))
print "New reduced limit:", resource.getrlimit(resource.RLIMIT_STACK)

# Normal use of python-ics
device = ics.find_devices()[0]
ics.open_device(device)
print ics.get_messages(device)
```

Without my fix, the last line `ics,get_message()` will cause python to exit with SIGSEGV.

SIGSEGV/139 is usually because the program attempt to access a virtual address which is not in his address space

**Comment by drebbe-intrepid** [comment]
Thanks for a way to reproduce this, I haven't had a chance to look into this. Hopefully in the next week or so I'll have this merged in.

As a side note you can just call open_device with no parameters and it will present a better exception instead of an index error if nothing was found.
`device = ics.open_device()`

**Comment by drebbe-intrepid** [comment]
This fix is in version 2.7.

**Pull request merged**
