### PR TITLE
Fix warning "invalid suffix on literal"

### PR DESCRIPTION
**Pull request by Alexpux**
Fix warnings: ````invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]````

### CODE REVIEW

**Comment by Alexpux** [comment]
Ping

**Comment by drebbe-intrepid** [comment]
@Alexpux sorry this one slipped by. Can you let me know what compiler you are using and what OS?

**Comment by drebbe-intrepid** [comment]
I'm going to try and work this in near the end of the week.

**Comment by Alexpux** [comment]
I’m use Windows. Toolchain is mingw-w64 GCC 8.2.1

**Pull request merged**
